OrdererOrgs:
  - Name: OrdererOrg
    Domain: vaultchain.local
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost

PeerOrgs:
  - Name: CreatorsOrg
    Domain: creators.vaultchain.local
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1

  - Name: AuthenticatorsOrg
    Domain: authenticators.vaultchain.local
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
