spring:
  application:
    name: authvault

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:authvault.db

    hikari:
      maximum-pool-size: 1

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: CHANGE_ME_TO_A_LONG_RANDOM_SECRET
  expiration: 86400000
