package com.authvault.dto.originality;

public enum OriginalityReasonCode {
    EXACT_SHA256_MATCH,
    BLOCKCHAIN_EXACT_MATCH_NOT_FOUND,
    REGISTERED_SOURCE_FOUND,
    PHASH_EXACT_VISUAL_HASH,
    PHASH_NEAR_DUPLICATE,
    PHASH_POSSIBLE_MATCH,
    SHA256_DIFFERENT,
    NO_PLAUSIBLE_REGISTERED_SOURCE,
    MEANINGFUL_CHANGES_DETECTED,
    COMPARISON_LOW_RELIABILITY,
    REGISTERED_ORIGINAL_CONTENT_UNAVAILABLE,
    BLOCKCHAIN_DISABLED,
    BLOCKCHAIN_UNAVAILABLE,
    BLOCKCHAIN_INVALID_RESPONSE,
    PHASH_UNAVAILABLE,
    COMPARISON_UNAVAILABLE
}
